export const GET_ARTICLES = "GET_ARTICLES"
export const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST"
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS"
export const GET_CURRENT_ART = "GET_CURRENT_ART"